# Generated by Django 5.2.8 on 2026-03-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='points',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
